"""Ports examples/win32.py onto the pure Python reader.

    python research/port_win32.py

Writes research/win32pure.py. The two readers offer the same names, so the
port is a handful of substitutions rather than a fork; this script exists so
that the difference stays visible and can be re-applied when win32.py changes.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, os.pardir, "examples", "win32.py")
TARGET = os.path.join(HERE, "win32pure.py")

IMPORTS = """from purewinmd import (  # the pure Python reader
    ElementType,
    TYPE_SPEC,
    TypeLayout,
    cache,
    category,
    coded_index as coded_index_TypeDefOrRef,
    find,
    get_attribute,
    get_category,
)
"""

SUBSTITUTIONS = [
    # the reader itself
    (re.compile(r"from winmd\.reader import \([^)]*\)\n", re.S), IMPORTS),
    # coded_index.type() gives a table number rather than a TypeDefOrRef member
    (re.compile(r"TypeDefOrRef\.TypeSpec"), "TYPE_SPEC"),
    # the module documents itself as the pure port
    (re.compile(r'^"""The Win32 API, resolved from the metadata'),
     '"""The Win32 API on the pure Python reader (research/purewinmd.py).\n\nGenerated by research/port_win32.py from examples/win32.py.\n\nThe Win32 API, resolved from the metadata'),
]


def main():
    with open(SOURCE, encoding="utf-8") as handle:
        source = handle.read()

    for pattern, replacement in SUBSTITUTIONS:
        source, count = pattern.subn(replacement, source, count=1 if pattern.pattern.startswith("from winmd") or pattern.pattern.startswith('^"""') else 0)
        if not count:
            raise SystemExit(f"nothing matched {pattern.pattern[:40]!r}")

    source = "import os\nimport sys\n\nsys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n\n" + source

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(source)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
